    # Ballerina demo config file
    consumerKey = "mLr4Ev3BGLItbXdD3h3VLxYfC"
    consumerSecret = "CtEI0CaqXNpjXC7LycdVYBkUysUOHtCitwnMYAaude35z3BLHo"
    accessToken = "969058561425735680-UEZYxUgUkSjBA0BhmtQ6CehvqpJG7V7"
    accessTokenSecret = "x0dixIonuDy6a8ES5Fc1uyLRYFkY4yIlQL1em0tmcpTvH"